import { Router } from 'express';
import authRoutes from './auth.routes';
import diaryRoutes from './diary.routes';
import tradeRoutes from './trade.routes';
import planRoutes from './plan.routes';
import statisticsRoutes from './statistics.routes';
import tagRoutes from './tag.routes';
import searchRoutes from './search.routes';
import exportRoutes from './export.routes';
import userRoutes from './user.routes';
import reportRoutes from './report.routes';
import reviewRoutes from './review.routes';
import reminderRoutes from './reminder.routes';
import stockRoutes from './stock.routes';
import analysisRoutes from './analysis.routes';
import accountRoutes from './account.routes';
import backtestRoutes from './backtest.routes';
import positionRoutes from './position.routes';
import alertRoutes from './alert.routes';
import watchlistRoutes from './watchlist.routes';
import earningsRoutes from './earnings.routes';
import signalRoutes from './signal.routes';
import portfolioRoutes from './portfolio.routes';
import settingsRoutes from './settings.routes';
import goalRoutes from './goal.routes';
import noteRoutes from './note.routes';
import dividendRoutes from './dividend.routes';
import calendarEventRoutes from './calendarEvent.routes';
import simulatorRoutes from './simulator.routes';
import costRoutes from './cost.routes';
import journalRoutes from './journal.routes';
import marketRoutes from './market.routes';
import indicatorRoutes from './indicator.routes';
import importExportRoutes from './importExport.routes';
import watchlistGroupRoutes from './watchlistGroup.routes';
import strategyTemplateRoutes from './strategyTemplate.routes';
import tradingDashboardRoutes from './tradingDashboard.routes';
import correlationRoutes from './correlation.routes';
import behaviorRoutes from './behavior.routes';
import aiAnalysisRoutes from './aiAnalysis.routes';
import tradePlanTemplateRoutes from './tradePlanTemplate.routes';
import tradeReviewTemplateRoutes from './tradeReviewTemplate.routes';
import { authMiddleware } from '../middlewares';

const router = Router();

// Mount routes
router.use('/auth', authRoutes);
router.use('/diaries', diaryRoutes);
router.use('/trades', tradeRoutes);
router.use('/plans', planRoutes);
router.use('/statistics', statisticsRoutes);
router.use('/tags', tagRoutes);
router.use('/search', searchRoutes);
router.use('/export', exportRoutes);
router.use('/user', userRoutes);
router.use('/reports', reportRoutes);
router.use('/review', reviewRoutes);
router.use('/reminders', reminderRoutes);
router.use('/stocks', stockRoutes);
router.use('/analysis', analysisRoutes);
router.use('/accounts', accountRoutes);
router.use('/backtest', backtestRoutes);
router.use('/positions', positionRoutes);
router.use('/alerts', alertRoutes);
router.use('/watchlist', authMiddleware, watchlistRoutes);
router.use('/earnings', earningsRoutes);
router.use('/signals', signalRoutes);
router.use('/portfolio', portfolioRoutes);
router.use('/settings', authMiddleware, settingsRoutes);
router.use('/goals', authMiddleware, goalRoutes);
router.use('/notes', authMiddleware, noteRoutes);
router.use('/dividends', authMiddleware, dividendRoutes);
router.use('/calendar-events', authMiddleware, calendarEventRoutes);
router.use('/simulator', authMiddleware, simulatorRoutes);
router.use('/cost-records', authMiddleware, costRoutes);
router.use('/journals', authMiddleware, journalRoutes);
router.use('/market', marketRoutes);
router.use('/indicators', indicatorRoutes);
router.use('/data', importExportRoutes);
router.use('/watchlist-groups', watchlistGroupRoutes);
router.use('/strategies', strategyTemplateRoutes);
router.use('/dashboard', tradingDashboardRoutes);
router.use('/correlation', correlationRoutes);
router.use('/behavior', behaviorRoutes);
router.use('/ai-analysis', aiAnalysisRoutes);

export default router;
